#pragma once

#include <SDL.h>

#define KEY_ESC SDL_SCANCODE_ESCAPE
#define KEY_1 SDL_SCANCODE_1
#define KEY_2 SDL_SCANCODE_2
#define KEY_3 SDL_SCANCODE_3
#define KEY_4 SDL_SCANCODE_4
#define KEY_5 SDL_SCANCODE_5
#define KEY_6 SDL_SCANCODE_6
#define KEY_7 SDL_SCANCODE_7
#define KEY_8 SDL_SCANCODE_8
#define KEY_9 SDL_SCANCODE_9
#define KEY_0 SDL_SCANCODE_0
#define KEY_MINUS SDL_SCANCODE_MINUS
#define KEY_EQUAL SDL_SCANCODE_EQUALS
#define KEY_BACKSPACE SDL_SCANCODE_BACKSPACE
#define KEY_TAB SDL_SCANCODE_TAB
#define KEY_Q SDL_SCANCODE_Q
#define KEY_W SDL_SCANCODE_W
#define KEY_E SDL_SCANCODE_E
#define KEY_R SDL_SCANCODE_R
#define KEY_T SDL_SCANCODE_T
#define KEY_Y SDL_SCANCODE_Y
#define KEY_U SDL_SCANCODE_U
#define KEY_I SDL_SCANCODE_I
#define KEY_O SDL_SCANCODE_O
#define KEY_P SDL_SCANCODE_P
#define KEY_LEFTBRACE SDL_SCANCODE_LEFTBRACKET
#define KEY_RIGHTBRACE SDL_SCANCODE_RIGHTBRACKET
#define KEY_ENTER SDL_SCANCODE_RETURN
#define KEY_LEFTCTRL SDL_SCANCODE_LCTRL
#define KEY_A SDL_SCANCODE_A
#define KEY_S SDL_SCANCODE_S
#define KEY_D SDL_SCANCODE_D
#define KEY_F SDL_SCANCODE_F
#define KEY_G SDL_SCANCODE_G
#define KEY_H SDL_SCANCODE_H
#define KEY_J SDL_SCANCODE_J
#define KEY_K SDL_SCANCODE_K
#define KEY_L SDL_SCANCODE_L
#define KEY_SEMICOLON SDL_SCANCODE_SEMICOLON
#define KEY_APOSTROPHE SDL_SCANCODE_APOSTROPHE
#define KEY_GRAVE SDL_SCANCODE_GRAVE
#define KEY_LEFTSHIFT SDL_SCANCODE_LSHIFT
#define KEY_BACKSLASH SDL_SCANCODE_BACKSLASH
#define KEY_Z SDL_SCANCODE_Z
#define KEY_X SDL_SCANCODE_X
#define KEY_C SDL_SCANCODE_C
#define KEY_V SDL_SCANCODE_V
#define KEY_B SDL_SCANCODE_B
#define KEY_N SDL_SCANCODE_N
#define KEY_M SDL_SCANCODE_M
#define KEY_COMMA SDL_SCANCODE_COMMA
#define KEY_DOT SDL_SCANCODE_PERIOD
#define KEY_SLASH SDL_SCANCODE_SLASH
#define KEY_RIGHTSHIFT SDL_SCANCODE_RSHIFT
#define KEY_KPASTERISK SDL_SCANCODE_KP_MULTIPLY
#define KEY_LEFTALT SDL_SCANCODE_LALT
#define KEY_SPACE SDL_SCANCODE_SPACE
#define KEY_CAPSLOCK SDL_SCANCODE_CAPSLOCK
#define KEY_F1 SDL_SCANCODE_F1
#define KEY_F2 SDL_SCANCODE_F2
#define KEY_F3 SDL_SCANCODE_F3
#define KEY_F4 SDL_SCANCODE_F4
#define KEY_F5 SDL_SCANCODE_F5
#define KEY_F6 SDL_SCANCODE_F6
#define KEY_F7 SDL_SCANCODE_F7
#define KEY_F8 SDL_SCANCODE_F8
#define KEY_F9 SDL_SCANCODE_F9
#define KEY_F10 SDL_SCANCODE_F10
#define KEY_NUMLOCK SDL_SCANCODE_NUMLOCK
#define KEY_SCROLLLOCK SDL_SCANCODE_SCROLLLOCK
#define KEY_KP7 SDL_SCANCODE_KP_7
#define KEY_KP8 SDL_SCANCODE_KP_8
#define KEY_KP9 SDL_SCANCODE_KP_9
#define KEY_KPMINUS SDL_SCANCODE_KP_MINUS
#define KEY_KP4 SDL_SCANCODE_KP_4
#define KEY_KP5 SDL_SCANCODE_KP_5
#define KEY_KP6 SDL_SCANCODE_KP_6
#define KEY_KPPLUS SDL_SCANCODE_KP_PLUS
#define KEY_KP1 SDL_SCANCODE_KP_1
#define KEY_KP2 SDL_SCANCODE_KP_2
#define KEY_KP3 SDL_SCANCODE_KP_3
#define KEY_KP0 SDL_SCANCODE_KP_0
#define KEY_KPDOT SDL_SCANCODE_KP_PERIOD

#define KEY_ZENKAKUHANKAKU SDL_SCANCODE_ZENKAKUHANKAKU
#define KEY_102ND SDL_SCANCODE_102ND
#define KEY_F11 SDL_SCANCODE_F11
#define KEY_F12 SDL_SCANCODE_F12
#define KEY_RO SDL_SCANCODE_RO
#define KEY_KATAKANA SDL_SCANCODE_KATAKANA
#define KEY_HIRAGANA SDL_SCANCODE_HIRAGANA
#define KEY_HENKAN SDL_SCANCODE_HENKAN
#define KEY_KATAKANAHIRAGANA SDL_SCANCODE_KATAKANAHIRAGANA
#define KEY_MUHENKAN SDL_SCANCODE_MUHENKAN
#define KEY_KPJPCOMMA SDL_SCANCODE_KPJPCOMMA
#define KEY_KPENTER SDL_SCANCODE_KP_ENTER
#define KEY_RIGHTCTRL SDL_SCANCODE_RCTRL
#define KEY_KPSLASH SDL_SCANCODE_KP_DIVIDE
#define KEY_SYSRQ SDL_SCANCODE_SYSRQ
#define KEY_RIGHTALT SDL_SCANCODE_RALT
#define KEY_LINEFEED SDL_SCANCODE_RETURN
#define KEY_HOME SDL_SCANCODE_HOME
#define KEY_UP SDL_SCANCODE_UP
#define KEY_PAGEUP SDL_SCANCODE_PAGEUP
#define KEY_LEFT SDL_SCANCODE_LEFT
#define KEY_RIGHT SDL_SCANCODE_RIGHT
#define KEY_END SDL_SCANCODE_END
#define KEY_DOWN SDL_SCANCODE_DOWN
#define KEY_PAGEDOWN SDL_SCANCODE_PAGEDOWN
#define KEY_INSERT SDL_SCANCODE_INSERT
#define KEY_DELETE SDL_SCANCODE_DELETE
#define KEY_MACRO SDL_SCANCODE_MACRO
#define KEY_MUTE SDL_SCANCODE_MUTE
#define KEY_VOLUMEDOWN SDL_SCANCODE_VOLUMEDOWN
#define KEY_VOLUMEUP SDL_SCANCODE_VOLUMEUP
#define KEY_POWER SDL_SCANCODE_POWER /* SC System Power Down */
#define KEY_KPEQUAL SDL_SCANCODE_KP_EQUALS
#define KEY_KPPLUSMINUS SDL_SCANCODE_KP_PLUSMINUS
#define KEY_PAUSE SDL_SCANCODE_PAUSE
#define KEY_SCALE SDL_SCANCODE_SCALE /* AL Compiz Scale (Expose) */

#define KEY_KPCOMMA SDL_SCANCODE_KPCOMMA
#define KEY_HANGEUL SDL_SCANCODE_HANGEUL
#define KEY_HANGUEL KEY_HANGEUL
#define KEY_HANJA SDL_SCANCODE_HANJA
#define KEY_YEN SDL_SCANCODE_YEN
#define KEY_LEFTMETA SDL_SCANCODE_LEFTMETA
#define KEY_RIGHTMETA SDL_SCANCODE_RIGHTMETA
#define KEY_COMPOSE SDL_SCANCODE_COMPOSE

#define KEY_STOP SDL_SCANCODE_STOP /* AC Stop */
#define KEY_AGAIN SDL_SCANCODE_AGAIN
#define KEY_PROPS SDL_SCANCODE_PROPS /* AC Properties */
#define KEY_UNDO SDL_SCANCODE_UNDO   /* AC Undo */
#define KEY_FRONT SDL_SCANCODE_FRONT
#define KEY_COPY SDL_SCANCODE_COPY   /* AC Copy */
#define KEY_OPEN SDL_SCANCODE_OPEN   /* AC Open */
#define KEY_PASTE SDL_SCANCODE_PASTE /* AC Paste */
#define KEY_FIND SDL_SCANCODE_FIND   /* AC Search */
#define KEY_CUT SDL_SCANCODE_CUT     /* AC Cut */
#define KEY_HELP SDL_SCANCODE_HELP   /* AL Integrated Help Center */
#define KEY_MENU SDL_SCANCODE_MENU   /* Menu (show menu) */
#define KEY_CALC SDL_SCANCODE_CALC   /* AL Calculator */
#define KEY_SETUP SDL_SCANCODE_SETUP
#define KEY_SLEEP SDL_SCANCODE_SLEEP   /* SC System Sleep */
#define KEY_WAKEUP SDL_SCANCODE_WAKEUP /* System Wake Up */
#define KEY_FILE SDL_SCANCODE_FILE     /* AL Local Machine Browser */
#define KEY_SENDFILE SDL_SCANCODE_SENDFILE
#define KEY_DELETEFILE SDL_SCANCODE_DELETEFILE
#define KEY_XFER SDL_SCANCODE_XFER
#define KEY_PROG1 SDL_SCANCODE_PROG1
#define KEY_PROG2 SDL_SCANCODE_PROG2
#define KEY_WWW SDL_SCANCODE_WWW /* AL Internet Browser */
#define KEY_MSDOS SDL_SCANCODE_MSDOS
#define KEY_COFFEE SDL_SCANCODE_COFFEE /* AL Terminal Lock/Screensaver */
#define KEY_SCREENLOCK KEY_COFFEE
#define KEY_ROTATE_DISPLAY                                                     \
  SDL_SCANCODE_ROTATE_DISPLAY /* Display orientation for e.g. tablets */
#define KEY_DIRECTION KEY_ROTATE_DISPLAY
#define KEY_CYCLEWINDOWS SDL_SCANCODE_CYCLEWINDOWS
#define KEY_MAIL SDL_SCANCODE_MAIL
#define KEY_BOOKMARKS SDL_SCANCODE_BOOKMARKS /* AC Bookmarks */
#define KEY_COMPUTER SDL_SCANCODE_COMPUTER
#define KEY_BACK SDL_SCANCODE_BACK       /* AC Back */
#define KEY_FORWARD SDL_SCANCODE_FORWARD /* AC Forward */
#define KEY_CLOSECD SDL_SCANCODE_CLOSECD
#define KEY_EJECTCD SDL_SCANCODE_EJECTCD
#define KEY_EJECTCLOSECD SDL_SCANCODE_EJECTCLOSECD
#define KEY_NEXTSONG SDL_SCANCODE_NEXTSONG
#define KEY_PLAYPAUSE SDL_SCANCODE_PLAYPAUSE
#define KEY_PREVIOUSSONG SDL_SCANCODE_PREVIOUSSONG
#define KEY_STOPCD SDL_SCANCODE_STOPCD
#define KEY_RECORD SDL_SCANCODE_RECORD
#define KEY_REWIND SDL_SCANCODE_REWIND
#define KEY_PHONE SDL_SCANCODE_PHONE /* Media Select Telephone */
#define KEY_ISO SDL_SCANCODE_ISO
#define KEY_CONFIG SDL_SCANCODE_CONFIG /* AL Consumer Control Configuration */
#define KEY_HOMEPAGE SDL_SCANCODE_HOMEPAGE /* AC Home */
#define KEY_REFRESH SDL_SCANCODE_REFRESH   /* AC Refresh */
#define KEY_EXIT SDL_SCANCODE_EXIT         /* AC Exit */
#define KEY_MOVE SDL_SCANCODE_MOVE
#define KEY_EDIT SDL_SCANCODE_EDIT
#define KEY_SCROLLUP SDL_SCANCODE_SCROLLUP
#define KEY_SCROLLDOWN SDL_SCANCODE_SCROLLDOWN
#define KEY_KPLEFTPAREN SDL_SCANCODE_KPLEFTPAREN
#define KEY_KPRIGHTPAREN SDL_SCANCODE_KPRIGHTPAREN
#define KEY_NEW SDL_SCANCODE_NEW   /* AC New */
#define KEY_REDO SDL_SCANCODE_REDO /* AC Redo/Repeat */
