#!/usr/bin/env python3
"""Regenerate sources.nix from koreader-base's thirdparty DOWNLOAD pins.

koreader-base's CMake build fetches each vendored thirdparty library itself
(via a custom `external_project()` CMake function) instead of vendoring
sources in the repo. This script parses those DOWNLOAD directives and emits
nix fetcher expressions for them, so the sandboxed nix build can pre-populate
the sources instead of reaching the network mid-build.

Usage:
    generate-sources.py <path-to-koreader-base-checkout> <git-rev> > sources.nix
"""

import re
import subprocess
import sys

DOWNLOAD_RE = re.compile(
    r"DOWNLOAD\s+(URL|GIT)\s+(\S+)\s+(\S+)",
    re.MULTILINE,
)

FULL_SHA_RE = re.compile(r"^[0-9a-f]{40}$")


def list_thirdparty_dirs(repo: str, rev: str) -> list[str]:
    out = subprocess.run(
        ["git", "-C", repo, "ls-tree", "--name-only", rev, "thirdparty/"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    return sorted(
        name.rstrip("/")
        for name in out.splitlines()
        if not name.startswith("thirdparty/cmake_modules")
    )


def read_file(repo: str, rev: str, path: str) -> str:
    return subprocess.run(
        ["git", "-C", repo, "show", f"{rev}:{path}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout


def nix_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    repo, rev = sys.argv[1], sys.argv[2]

    entries = []
    for path in list_thirdparty_dirs(repo, rev):
        cmake_path = f"{path}/CMakeLists.txt"
        try:
            content = read_file(repo, rev, cmake_path)
        except subprocess.CalledProcessError:
            continue
        m = DOWNLOAD_RE.search(content)
        if not m:
            continue
        name = path.split("/", 1)[1]
        method, a, b = m.groups()
        if method == "URL":
            entries.append(("url", name, {"md5": a, "url": b}))
        else:
            rev_or_tag, remote = a, b
            entries.append(
                (
                    "git-sha" if FULL_SHA_RE.match(rev_or_tag) else "git-tag",
                    name,
                    {"rev": rev_or_tag, "url": remote},
                )
            )

    url_entries = [(n, d) for k, n, d in entries if k == "url"]
    git_entries = [(n, d) for k, n, d in entries if k in ("git-sha", "git-tag")]

    print("# Generated by generate-sources.py — do not edit by hand.")
    print(f"# Source: koreader-base @ {rev}")
    print("{ fetchurl, fetchgit }:")
    print("{")
    print("  # Tarball/zip downloads (`DOWNLOAD URL <md5> <url>` in koreader-base).")
    print("  # Each fetches to base/thirdparty/<name>/build/downloads/<basename>.")
    print("  urlSources = {")
    for name, data in url_entries:
        print(f"    {name} = fetchurl {{")
        print(f"      url = {nix_str(data['url'])};")
        print(f"      # upstream md5: {data['md5']}")
        print('      hash = ""; # FIXME: run nix store prefetch-file and fill in')
        print("    };")
    print("  };")
    print()
    print("  # Git checkouts (`DOWNLOAD GIT <rev> <remote>` in koreader-base).")
    print("  # Each fetches to base/thirdparty/<name>/build/downloads/source.")
    print("  gitSources = {")
    for name, data in git_entries:
        # fetchgit (not builtins.fetchGit): more reliable submodule handling
        # for repos with deeply/awkwardly-pinned nested submodules.
        print(f"    {name} = fetchgit {{")
        print(f"      url = {nix_str(data['url'])};")
        print(f"      rev = {nix_str(data['rev'])};")
        print('      hash = ""; # FIXME: run `nix-prefetch-git` and fill in')
        print("      fetchSubmodules = true;")
        print("    };")
    print("  };")
    print("}")


if __name__ == "__main__":
    main()
