# Generated by generate-sources.py — do not edit by hand.
# Source: koreader-base @ 6e4bc81af4e04f78d81677a323a780a71b29702a
{ fetchurl, fetchgit }:
{
  # Tarball/zip downloads (`DOWNLOAD URL <md5> <url>` in koreader-base).
  # Each fetches to base/thirdparty/<name>/build/downloads/<basename>.
  urlSources = {
    brotli = fetchurl {
      url = "https://github.com/google/brotli/archive/refs/tags/v1.1.0.tar.gz";
      # upstream md5: 3a6a3dba82a3604792d3cb0bd41bca60
      hash = "sha256-5yCmyilCi4A/StFlNxdx9TmPq6OX7fZ3iDehhZnqE/8="; # FIXME: run nix store prefetch-file and fill in
    };
    certifi = fetchurl {
      url = "https://files.pythonhosted.org/packages/ef/2f/c5464532e965badff2f4c4c1a3a83f5697f0d7c407ed0cda44aaa99bb451/certifi-2026.6.17-py3-none-any.whl";
      # upstream md5: 3b14da8e2efaade7cd0ff168139c7868
      hash = "sha256-Iifcuq/g0vWSedF2Ld3cN3g+1DVFlPGU/8MdIPQfw9s="; # FIXME: run nix store prefetch-file and fill in
    };
    cpu_features = fetchurl {
      url = "https://github.com/google/cpu_features/archive/refs/tags/v0.10.1.tar.gz";
      # upstream md5: 32f6f561c24dce66ed4bc0384b22c026
      hash = "sha256-UmObOA/O0R1zj4sVHb/uY/uUlXcx0H8ZZsgS5bkMutQ="; # FIXME: run nix store prefetch-file and fill in
    };
    curl = fetchurl {
      url = "https://github.com/curl/curl/releases/download/curl-8_14_1/curl-8.14.1.tar.xz";
      # upstream md5: cba9ea54bccefed639a529b1b5b17405
      hash = "sha256-9GGaHiR0xLv+3IinwhkSCcgzS0j6H05T/VhMwS6RIN0="; # FIXME: run nix store prefetch-file and fill in
    };
    czmq = fetchurl {
      url = "https://github.com/zeromq/czmq/releases/download/v4.2.1/czmq-4.2.1.tar.gz";
      # upstream md5: 471e9ec120fc66a2fe2aae14359e3cfa
      hash = "sha256-XXIKIEwqWGRdb3ZDrxXVY6cS2tmMnTLB7ZEzd9qmrDk="; # FIXME: run nix store prefetch-file and fill in
    };
    dkjson = fetchurl {
      url = "http://dkolf.de/dkjson-lua/dkjson-2.10.tar.gz";
      # upstream md5: eededec0ec8befa97fc88947a668b5e6
      hash = "sha256-6MeeBrXEhWQzllCPTEXm0e7GhdCL++dwQvQfOEJNWyQ="; # FIXME: run nix store prefetch-file and fill in
    };
    dropbear = fetchurl {
      url = "https://github.com/mkj/dropbear/archive/refs/tags/DROPBEAR_2026.92.tar.gz";
      # upstream md5: 26c3e2ea61a8f3bc5b19c78e697ec42c
      hash = "sha256-YaqdSLhd5k/sM/6z4qXZqY43Gm8LYvM+6Pxqztg4t7w="; # FIXME: run nix store prefetch-file and fill in
    };
    freetype2 = fetchurl {
      url = "https://github.com/freetype/freetype/archive/refs/tags/VER-2-14-3.tar.gz";
      # upstream md5: 0f816defb4d1d7dd274df0937431916f
      hash = "sha256-3EneawGiZu70h2pN002YQsR10+KP8u/2O9L7dgq1YmE="; # FIXME: run nix store prefetch-file and fill in
    };
    fribidi = fetchurl {
      url = "https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz";
      # upstream md5: 333ad150991097a627755b752b87f9ff
      hash = "sha256-GxzeWyNdQEeekb4vDoijCeMhTIq0cOyKJ0TYKlqeoFw="; # FIXME: run nix store prefetch-file and fill in
    };
    giflib = fetchurl {
      url = "https://sourceforge.net/projects/giflib/files/giflib-6.x/giflib-6.1.3.tar.gz";
      # upstream md5: a70e90ff780e9ebee9cb84b82bbd46a7
      hash = "sha256-tltmuZ8EJLk1JfmHOG8i/F77naK/ySrUpTIkmq/7qw4="; # FIXME: run nix store prefetch-file and fill in
    };
    glib = fetchurl {
      url = "https://download.gnome.org/sources/glib/2.82/glib-2.82.1.tar.xz";
      # upstream md5: d101f1acab6805d4d6d3104e9634b8e3
      hash = "sha256-R4Y0RAv1LuTsRCjVWHhzmMC+awQ8UhvrMIM0s9tEiaY="; # FIXME: run nix store prefetch-file and fill in
    };
    harfbuzz = fetchurl {
      url = "https://github.com/harfbuzz/harfbuzz/releases/download/14.2.1/harfbuzz-14.2.1.tar.xz";
      # upstream md5: dda477eb1b44ac816ec1a8e4effee1af
      hash = "sha256-pUpdjpOApB+7dizjZ7y/dwR5Lfyg2T8bvKhsWleQLg4="; # FIXME: run nix store prefetch-file and fill in
    };
    leptonica = fetchurl {
      url = "https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.87.0.tar.gz";
      # upstream md5: 1f66c425c270e9793982289e1ff9634a
      hash = "sha256-+itAxcrqltG7k6l0hiYq7YcxtpziWoSmv10lMj4z9jE="; # FIXME: run nix store prefetch-file and fill in
    };
    libarchive = fetchurl {
      url = "https://github.com/libarchive/libarchive/releases/download/v3.8.8/libarchive-3.8.8.tar.xz";
      # upstream md5: 81a6d70daf20671ea2c5cd4bb1d371ae
      hash = "sha256-OHOoiAHaBn0FKKmJrwaHdxBSnVDuj+bzlwy7QwLvuRg="; # FIXME: run nix store prefetch-file and fill in
    };
    libjpeg-turbo = fetchurl {
      url = "https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/3.2.0/libjpeg-turbo-3.2.0.tar.gz";
      # upstream md5: a80f9f1c735b57d3cdd66daed1ba6bb4
      hash = "sha256-bzAJLO+fuDl3lkZgj07hSuPLrJicR/oF6EGwhB8Jh44="; # FIXME: run nix store prefetch-file and fill in
    };
    libpng = fetchurl {
      url = "https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.58.tar.gz";
      # upstream md5: 92972b05f1895240139f749ff24afce8
      hash = "sha256-qdTfRj02puX5wpvW9JZzEtF+mWwYVPNRH4M5JOsZk88="; # FIXME: run nix store prefetch-file and fill in
    };
    libressl = fetchurl {
      url = "https://cdn.openbsd.org/pub/OpenBSD/LibreSSL/libressl-4.3.2.tar.gz";
      # upstream md5: 52d53fe0cd880a7276a4a2f9cd1fa29f
      hash = "sha256-7fAa7iTGXWnmqe/LnUS82mgv+dTzu72V55Th36kIR7U="; # FIXME: run nix store prefetch-file and fill in
    };
    libunibreak = fetchurl {
      url = "https://github.com/adah1972/libunibreak/releases/download/libunibreak_7_0/libunibreak-7.0.tar.gz";
      # upstream md5: ccc11ff950ef7aefa815035f3a20de57
      hash = "sha256-jJpuEhc2zQ1ciQrjrpbz9AEKGaoEDx297YM6Yqh3F9M="; # FIXME: run nix store prefetch-file and fill in
    };
    libwebp = fetchurl {
      url = "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.6.0.tar.gz";
      # upstream md5: cceb6447180f961473b181c9ef38b630
      hash = "sha256-5KtwCb8GKf0RmC1MKqg5ZM8kTP+6c0fs05AZqeOMRWQ="; # FIXME: run nix store prefetch-file and fill in
    };
    libzmq = fetchurl {
      url = "https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz";
      # upstream md5: ae933b1e98411fd7cb8309f9502d2737
      hash = "sha256-ZlPvWRDxeVSGH+cjMuaLA8puTZxxYOs6jeWlqRO/q0M="; # FIXME: run nix store prefetch-file and fill in
    };
    lpeg = fetchurl {
      url = "https://github.com/roberto-ieru/LPeg/archive/refs/tags/v1.1.0.tar.gz";
      # upstream md5: c9914cc6036d4afa2f49e5c659a214a5
      hash = "sha256-ibzVbGy30AHBL9LAxIbAbKgoP4tYmG9ZPWLMJuFFjeQ="; # FIXME: run nix store prefetch-file and fill in
    };
    luarocks = fetchurl {
      url = "https://github.com/luarocks/luarocks/archive/refs/tags/v3.12.2.tar.gz";
      # upstream md5: 56d10945997f2eab5922f24195550a1d
      hash = "sha256-nCX6erUBfWCyUTerGky3bjGF3x/gLfH1d/V9GmtUiio="; # FIXME: run nix store prefetch-file and fill in
    };
    md4c = fetchurl {
      url = "https://github.com/mity/md4c/archive/refs/tags/release-0.5.3.tar.gz";
      # upstream md5: 04b54eb032d324be3d9307bda1125320
      hash = "sha256-NTw0bzdrh8lUoT80Fe3i1RJkzGHcWrzTj/HSqg0Fm54="; # FIXME: run nix store prefetch-file and fill in
    };
    miniconv = fetchurl {
      url = "https://github.com/malord/miniconv/archive/170ddcb9ac8eda1e08e7426acecb6a5733cf1d36.tar.gz";
      # upstream md5: 5871dfaced0f3d5f96c032f30b0590ae
      hash = "sha256-9rXXvDyhLApmBLOCo9rT1/kCr0CZc7d8tvp1QAVhIbk="; # FIXME: run nix store prefetch-file and fill in
    };
    mupdf = fetchurl {
      url = "https://github.com/ArtifexSoftware/mupdf-downloads/releases/download/1.27.2/mupdf-1.27.2-source.tar.lz";
      # upstream md5: 17169f89d135a9cb0de147690f982c88
      hash = "sha256-NQSdzQsaVBvizKHrS71rQaUeDtRHmTM7e95FKEYeKEg="; # FIXME: run nix store prefetch-file and fill in
    };
    openssh = fetchurl {
      url = "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-10.4p1.tar.gz";
      # upstream md5: c5fb91ded926b38e8956074cac2cd44f
      hash = "sha256-72Am3SrqjVYFljjV0yYpAsiSzrqfiDlYNeDQbT+2Mjg="; # FIXME: run nix store prefetch-file and fill in
    };
    proxy-libintl = fetchurl {
      url = "https://github.com/frida/proxy-libintl/archive/refs/tags/0.4.tar.gz";
      # upstream md5: 7cc93d2fec98a5b9820888135d2e8844
      hash = "sha256-E+8+6go7wN9VKTvjaN+8/1qN1fR1koDyjgMNFJSl3/s="; # FIXME: run nix store prefetch-file and fill in
    };
    sdcv = fetchurl {
      url = "https://github.com/Dushistov/sdcv/archive/refs/tags/v0.5.5.tar.gz";
      # upstream md5: 265dbfda83a57810595d156877f3e6fd
      hash = "sha256-TSUZ6PhHm5MB3JHpzaPh7v7xmXDs4OjAXwx7et5dyUs="; # FIXME: run nix store prefetch-file and fill in
    };
    sdl3 = fetchurl {
      url = "https://github.com/libsdl-org/SDL/releases/download/release-3.4.12/SDL3-3.4.12.tar.gz";
      # upstream md5: 6ad7c4fc2b36a9e073f23dfb8765f7ea
      hash = "sha256-8HuViprFAg+3pEytuVf2WLIUnDyKu09jFF+skwMknbc="; # FIXME: run nix store prefetch-file and fill in
    };
    sqlite = fetchurl {
      url = "https://www.sqlite.org/2026/sqlite-amalgamation-3530300.zip";
      # upstream md5: b43f1b254ab1ad9b22b0389995311b87
      hash = "sha256-ZGQh4SqsEQKC74zGjxpi1LsV/HuPCdoLU+Ke5pBQBDE="; # FIXME: run nix store prefetch-file and fill in
    };
    tar = fetchurl {
      url = "http://ftpmirror.gnu.org/tar/tar-1.34.tar.gz";
      # upstream md5: 9d5949e4c2d9665546ac65dafc0e726a
      hash = "sha256-A9kIz1doz+a3rViMkhxu0hrKv7K3m3iNEzBFNQdkeu0="; # FIXME: run nix store prefetch-file and fill in
    };
    tesseract = fetchurl {
      url = "https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.5.2.tar.gz";
      # upstream md5: ee8efb2b71dc79eb56cd02ced84a31d5
      hash = "sha256-YjXqDa5F6hN/WcCTIEBvWIg4N0GSTZiFW9LODRa1TyE="; # FIXME: run nix store prefetch-file and fill in
    };
    tree-sitter = fetchurl {
      url = "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.26.10.tar.gz";
      # upstream md5: d98afafe16c700b75df5cab113fc471b
      hash = "sha256-RQy4X9GvNBEesWLpMeDp5NTb8j/Am5y1b2KZoagEg7Y="; # FIXME: run nix store prefetch-file and fill in
    };
    tree-sitter-c = fetchurl {
      url = "https://github.com/tree-sitter/tree-sitter-c/archive/refs/tags/v0.24.2.tar.gz";
      # upstream md5: 02c27c7a6f92ff9b3e201358d614a78d
      hash = "sha256-LutNsx+PoIZeRUiFA9E0A5I7y0haG9tjer/4xC3Zc2Q="; # FIXME: run nix store prefetch-file and fill in
    };
    utf8proc = fetchurl {
      url = "https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.11.3.tar.gz";
      # upstream md5: 09773a9a9c4029b1e547fe398e555411
      hash = "sha256-q/7VC21NpRNFcTZhNwKQ9PR0cmPuc9yQNWKZ38eZDHg="; # FIXME: run nix store prefetch-file and fill in
    };
    xxhash = fetchurl {
      url = "https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.3.tar.gz";
      # upstream md5: 599804eb9555e51c05f1b821f9212a07
      hash = "sha256-quYI3+ghPf0F2QmldxjvgvMHIsOSNEWD0/OQUMfymoA="; # FIXME: run nix store prefetch-file and fill in
    };
    xz = fetchurl {
      url = "https://github.com/tukaani-project/xz/releases/download/v5.8.3/xz-5.8.3.tar.xz";
      # upstream md5: a02753f34e5546d20213b87f876a0933
      hash = "sha256-//H/zysNqE0wihTeUToaoj1OmqNGTRfmS5cUv90Lv7Y="; # FIXME: run nix store prefetch-file and fill in
    };
    zlib = fetchurl {
      url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.xz";
      # upstream md5: be8a129ec5d60c5084911fd7ea16d84e
      hash = "sha256-16BlR4Ok2lKdG7eTt62cMxgCCvd2Z7yuNfldDkKnkvM="; # FIXME: run nix store prefetch-file and fill in
    };
    zstd = fetchurl {
      url = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz";
      # upstream md5: 780fc1896922b1bc52a4e90980cdda48
      hash = "sha256-6zPlH0mhXgI5UM14Jcp0pKK0Pbg1SCWsJPwbfuCeb6M="; # FIXME: run nix store prefetch-file and fill in
    };
  };

  # Git checkouts (`DOWNLOAD GIT <rev> <remote>` in koreader-base).
  # Each fetches to base/thirdparty/<name>/build/downloads/source.
  gitSources = {
    djvulibre = fetchgit {
      url = "https://gitlab.com/koreader/djvulibre.git";
      rev = "69e23da9876baa7fc052d6b2e03e62e3095ec2f1";
      hash = "sha256-XO3GHRbB4giiFhSRBn5OcujM3IdkunEkQ+NzkIop+3o="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    fbink = fetchgit {
      url = "https://github.com/NiLuJe/FBInk.git";
      rev = "92e127008145b2a22fba7c59815d810d716310dd";
      hash = "sha256-yUdEsFi/9OLKTtKjmldbWMzDsYX644/uIGixFAVamkw="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    inkview = fetchgit {
      url = "https://github.com/koreader/pocketbook-inkview.git";
      rev = "4a3e32c39ed14ac7f2e3ca4f8c66a7d5fbe5e0fe";
      hash = "sha256-xq9JsxLcENBWt0rjDGhu/itT8oPyd5LG2K/TWBiZQSk="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    kobo-usbms = fetchgit {
      url = "https://github.com/koreader/KoboUSBMS.git";
      rev = "d1d916655b1406780f12ba0c2442b6a901e75929";
      hash = "sha256-jYux6/xTC7CISi6TqN9EgQQafGJZNZPtwgdaozXjN3k="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    koreader-lfs = fetchgit {
      url = "https://github.com/lunarmodules/luafilesystem";
      rev = "a186cca5833691e830ed255e38ace8ff6b870dbf";
      hash = "sha256-aabznj5k6TMx153VeDBFedv7tFZzvgOkwo4yIEPy0t8="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    libk2pdfopt = fetchgit {
      url = "https://github.com/koreader/libk2pdfopt.git";
      rev = "1fcffeb1e61ec43265d23e2ac77d9a901f8c45d2";
      hash = "sha256-CuKpGOI7MfoQOsaeuF+8f2muWfXDoul0l3wgqjCQXYQ="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lj-wpaclient = fetchgit {
      url = "https://github.com/koreader/lj-wpaclient.git";
      rev = "0d5c8ee336b699dbb35850a7336d24e89e1aac24";
      hash = "sha256-m50+7D+LWl5LTqJttNUrHZnQM1FFXS9RbLglOuR9EQQ="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lodepng = fetchgit {
      url = "https://github.com/lvandeve/lodepng.git";
      rev = "0b1d9ccfc2093e5d6620cd9a11d03ee6ff6705f5";
      hash = "sha256-wskSBmAB/jT+t+ArGtLghSbdUAty9gbon8wMnpIeiYU="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lua-Spore = fetchgit {
      url = "https://framagit.org/fperrad/lua-Spore";
      rev = "f106f930e4fd6110f714dd89f8886e868c74a583";
      hash = "sha256-wjXF7oEpdcpt8jmCH2bVj6PijOQpkHJu+22+MS/AbYo="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lua-htmlparser = fetchgit {
      url = "https://github.com/msva/lua-htmlparser";
      rev = "5ce9a775a345cf458c0388d7288e246bb1b82bff";
      hash = "sha256-kMhS7uUVeYRYrJU7VsbRH0aC54F/jaVWh7pdelLmasQ="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lua-rapidjson = fetchgit {
      url = "https://github.com/NiLuJe/lua-rapidjson";
      rev = "e84973356255bde06a70ce6263a3a0ef5c8f4ad4";
      hash = "sha256-xsbf8AYTmGcKgNefFdQJ197aj9Z7BHvAYVgbjhAMfJ0="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luajit = fetchgit {
      url = "https://github.com/LuaJIT/LuaJIT";
      rev = "3c4f9fe2052b8d08a917ac0d5f38563f0297b5a3";
      hash = "sha256-cR240fEr6Oodl+acT+I/d1YjwKzgX/9P949jbDAOgFM="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luajson = fetchgit {
      url = "https://github.com/harningt/luajson.git";
      rev = "6ecaf9bea8b121a9ffca5a470a2080298557b55d";
      hash = "sha256-Y2GpaMWXoiGtbjlO8/NP/35PgRuzTkwXmxIetE8D+IM="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luasec = fetchgit {
      url = "https://github.com/brunoos/luasec";
      rev = "4c06287052d68fdbe7429b8f967cdc8ee94aa44a";
      hash = "sha256-sZu6acBs3Gy1h74sK7wU2NvPOd3kDaqeIeBKJ/pJv/E="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luasocket = fetchgit {
      url = "https://github.com/lunarmodules/luasocket";
      rev = "e3ca4a767a68d127df548d82669aba3689bd84f4";
      hash = "sha256-OFz07+Wdhiz/JhQ7AZjsklzM15Z9kJz2KUQpvcVnGsk="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lunasvg = fetchgit {
      url = "https://github.com/sammycage/lunasvg.git";
      rev = "610b8bf5148a27489b4e3344b4f5617b81be38c7";
      hash = "sha256-2kTGIkrcPsAcrCvUtUzUcgpqtCuCuLzs2Z0ImAlq00Y="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    minizip = fetchgit {
      url = "https://github.com/nmoinvaz/minizip";
      rev = "aa4758baea16e9dc03583340e62b370ea1140df9";
      hash = "sha256-scxgbWbZUTKRhbTeYCWkm7CLp0NOkGHSZleZHEv8VAc="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    nanosvg = fetchgit {
      url = "https://github.com/memononen/nanosvg.git";
      rev = "ea6a6aca009422bba0dbad4c80df6e6ba0c82183";
      hash = "sha256-zop4QF6gawQjjsVPb9xqfMqUSawACR6/qjArT1Noqu4="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    openlipclua = fetchgit {
      url = "https://github.com/notmarek/openlipclua.git";
      rev = "96c2d16696a482664b4e84eb3b6d851f807a44d1";
      hash = "sha256-oHHMXCZVuZp2CTqUOOjZ6UiDNK1eSa1w9TSDgi7+Yis="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    popen-noshell = fetchgit {
      url = "https://github.com/famzah/popen-noshell.git";
      rev = "e715396a4951ee91c40a98d2824a130f158268bb";
      hash = "sha256-oIAL6fMw6UfjG2CnV5zK1cZIkCdt68hEbq45dTRpSEM="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    turbo = fetchgit {
      url = "https://github.com/kernelsauce/turbo";
      rev = "7fe88c2b99ff9bd6d6df3ee3c4077ea8a7d1e6a3";
      hash = "sha256-4QbgBs/sUlaQ/SBQMUm/yvWnrjEUR1tQf1CHW8POO2g="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    zsync2 = fetchgit {
      url = "https://github.com/NiLuJe/zsync2.git";
      rev = "e281e1eb4466ff6b3866c25dbe62a3e150fa5bfd";
      hash = "sha256-p7nV17YfSPGi5A/L4h/T9HQJOmMqQNZv+iKvi3N2R9Y="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
  };
}
