# Generated by generate-sources.py — do not edit by hand.
# Source: koreader-base @ e64da86542f4af5adc8baed05fde048f2bae149c
{ fetchurl, fetchgit }:
{
  # Tarball/zip downloads (`DOWNLOAD URL <md5> <url>` in koreader-base).
  # Each fetches to base/thirdparty/<name>/build/downloads/<basename>.
  urlSources = {
    cpu_features = fetchurl {
      url = "https://github.com/google/cpu_features/archive/refs/tags/v0.10.1.tar.gz";
      # upstream md5: 32f6f561c24dce66ed4bc0384b22c026
      hash = "sha256-UmObOA/O0R1zj4sVHb/uY/uUlXcx0H8ZZsgS5bkMutQ="; # FIXME: run nix store prefetch-file and fill in
    };
    curl = fetchurl {
      url = "https://github.com/curl/curl/releases/download/curl-8_14_1/curl-8.14.1.tar.xz";
      # upstream md5: cba9ea54bccefed639a529b1b5b17405
      hash = "sha256-9GGaHiR0xLv+3IinwhkSCcgzS0j6H05T/VhMwS6RIN0="; # FIXME: run nix store prefetch-file and fill in
    };
    czmq = fetchurl {
      url = "https://github.com/zeromq/czmq/releases/download/v4.2.1/czmq-4.2.1.tar.gz";
      # upstream md5: 471e9ec120fc66a2fe2aae14359e3cfa
      hash = "sha256-XXIKIEwqWGRdb3ZDrxXVY6cS2tmMnTLB7ZEzd9qmrDk="; # FIXME: run nix store prefetch-file and fill in
    };
    dkjson = fetchurl {
      url = "http://dkolf.de/dkjson-lua/dkjson-2.8.tar.gz";
      # upstream md5: d7754634dcbe6e95f3b6b55fd4ca5ceb
      hash = "sha256-JOjNO+uRwchh63uz+8m9QYu/+a1KpdBHGBYlgjajFTI="; # FIXME: run nix store prefetch-file and fill in
    };
    dropbear = fetchurl {
      url = "https://github.com/mkj/dropbear/archive/refs/tags/DROPBEAR_2025.88.tar.gz";
      # upstream md5: 327e7deca6ce7c18b1f259dbf40021bd
      hash = "sha256-k+vhKU7jID079UjHjVG96UlNPyTeZOrsOAomIPBDHyA="; # FIXME: run nix store prefetch-file and fill in
    };
    freetype2 = fetchurl {
      url = "https://github.com/freetype/freetype/archive/refs/tags/VER-2-13-3.tar.gz";
      # upstream md5: 4425315beb50f913ae12d643e4e121e1
      hash = "sha256-vFyJjkdW03Pg2ZG6sFMDbF6yqnwNXGfoZi3cbaQMQQM="; # FIXME: run nix store prefetch-file and fill in
    };
    fribidi = fetchurl {
      url = "https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz";
      # upstream md5: 333ad150991097a627755b752b87f9ff
      hash = "sha256-GxzeWyNdQEeekb4vDoijCeMhTIq0cOyKJ0TYKlqeoFw="; # FIXME: run nix store prefetch-file and fill in
    };
    giflib = fetchurl {
      url = "https://sourceforge.net/projects/giflib/files/giflib-5.2.2.tar.gz";
      # upstream md5: 913dd251492134e235ee3c9a91987a4d
      hash = "sha256-vn/70FfK3r4qoURUL9kMaDjGoIO16KkEi47jtmsp1fs="; # FIXME: run nix store prefetch-file and fill in
    };
    glib = fetchurl {
      url = "https://download.gnome.org/sources/glib/2.82/glib-2.82.1.tar.xz";
      # upstream md5: d101f1acab6805d4d6d3104e9634b8e3
      hash = "sha256-R4Y0RAv1LuTsRCjVWHhzmMC+awQ8UhvrMIM0s9tEiaY="; # FIXME: run nix store prefetch-file and fill in
    };
    harfbuzz = fetchurl {
      url = "https://github.com/harfbuzz/harfbuzz/releases/download/11.2.1/harfbuzz-11.2.1.tar.xz";
      # upstream md5: 53d77e130fc16e95c4e8a09c0c6fbd85
      hash = "sha256-CTcUyFSKKFCUaF8L3JmeIC1ma1nus98v+SGraLgzakk="; # FIXME: run nix store prefetch-file and fill in
    };
    leptonica = fetchurl {
      url = "https://github.com/DanBloomberg/leptonica/archive/refs/tags/1.85.0.tar.gz";
      # upstream md5: 9450017d7c9269cae1fad59b6cd06a3e
      hash = "sha256-wBN2vOA3nU6kvC7F1cvdqkni8G+IJCYZq4wFniGt8jM="; # FIXME: run nix store prefetch-file and fill in
    };
    libarchive = fetchurl {
      url = "https://github.com/libarchive/libarchive/releases/download/v3.7.9/libarchive-3.7.9.tar.xz";
      # upstream md5: e378aeb163d8c81745665dddd81116ef
      hash = "sha256-7YtXMuTNbjD66Qn7lFytj/nLe+XGzao5ROyW5KIAwEw="; # FIXME: run nix store prefetch-file and fill in
    };
    libiconv = fetchurl {
      url = "http://ftpmirror.gnu.org/libiconv/libiconv-1.15.tar.gz";
      # upstream md5: ace8b5f2db42f7b3b3057585e80d9808
      hash = "sha256-zPU2YgpFRY0muoOIepg7loJwAekqE4R7ReSSXMiRMXg="; # FIXME: run nix store prefetch-file and fill in
    };
    libpng = fetchurl {
      url = "https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.50.tar.gz";
      # upstream md5: 4a6433f54317b8f0d4cb749c09d4eff2
      hash = "sha256-cRWOU8/fKHe8mbyrM2QdeN8/SObg2q0DCv6cuMAxqkY="; # FIXME: run nix store prefetch-file and fill in
    };
    libressl = fetchurl {
      url = "https://github.com/libressl/portable/releases/download/v4.1.0/libressl-4.1.0.tar.gz";
      # upstream md5: 18079dcf72a398d8c188e67e30c1dc13
      hash = "sha256-D3HBa9NL2qzNy5al2UpJIb+2EuxuDrp6gNiFTu/Yu2E="; # FIXME: run nix store prefetch-file and fill in
    };
    libunibreak = fetchurl {
      url = "https://github.com/adah1972/libunibreak/releases/download/libunibreak_6_1/libunibreak-6.1.tar.gz";
      # upstream md5: 8df410d010e03de1a339a400a920335e
      hash = "sha256-zE3gCZz3/wUAXOq/9K/tTFgqc2q8OAM+cP2shjNc6T8="; # FIXME: run nix store prefetch-file and fill in
    };
    libwebp = fetchurl {
      url = "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.6.0.tar.gz";
      # upstream md5: cceb6447180f961473b181c9ef38b630
      hash = "sha256-5KtwCb8GKf0RmC1MKqg5ZM8kTP+6c0fs05AZqeOMRWQ="; # FIXME: run nix store prefetch-file and fill in
    };
    libzmq = fetchurl {
      url = "https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz";
      # upstream md5: ae933b1e98411fd7cb8309f9502d2737
      hash = "sha256-ZlPvWRDxeVSGH+cjMuaLA8puTZxxYOs6jeWlqRO/q0M="; # FIXME: run nix store prefetch-file and fill in
    };
    lpeg = fetchurl {
      url = "http://distcache.FreeBSD.org/ports-distfiles/lpeg-1.1.0.tar.gz";
      # upstream md5: 842a538b403b5639510c9b6fffd2c75b
      hash = "sha256-SxVdZ9IkbB/6ete8RmweqJm7xA/vAlfMnAPOy67UNSo="; # FIXME: run nix store prefetch-file and fill in
    };
    luarocks = fetchurl {
      url = "https://github.com/luarocks/luarocks/archive/refs/tags/v3.11.1.tar.gz";
      # upstream md5: ab95865ced3c123908bd2f1fe6843606
      hash = "sha256-o35KP6qDXRtkN6stniJxkJZkq2FFlct98bZ92v5OIZM="; # FIXME: run nix store prefetch-file and fill in
    };
    md4c = fetchurl {
      url = "https://github.com/mity/md4c/archive/refs/tags/release-0.5.2.tar.gz";
      # upstream md5: 8ead909cfe31884295e81e2eee32bac9
      hash = "sha256-VdARHUj7EYg6rukUZeZCuLZAd1pNaZPC0OeoCSdY7yE="; # FIXME: run nix store prefetch-file and fill in
    };
    mupdf = fetchurl {
      url = "https://mupdf.com/downloads/archive/mupdf-1.26.3-source.tar.lz";
      # upstream md5: 8b4eb93f7174065715efac8fa3790b32
      hash = "sha256-OaO3VSxqK6dR5ltYtbClwXw4IHCw7v/AMlLZ/nLPlS8="; # FIXME: run nix store prefetch-file and fill in
    };
    openssh = fetchurl {
      url = "https://cdn.openbsd.org/pub/OpenBSD/OpenSSH/portable/openssh-10.0p1.tar.gz";
      # upstream md5: 689148621a2eaa734497b12bed1c5202
      hash = "sha256-AhoucJoO30JQsSVr1anlAEEakN3avqgw7VnO+Q652Fw="; # FIXME: run nix store prefetch-file and fill in
    };
    proxy-libintl = fetchurl {
      url = "https://github.com/frida/proxy-libintl/archive/refs/tags/0.4.tar.gz";
      # upstream md5: 7cc93d2fec98a5b9820888135d2e8844
      hash = "sha256-E+8+6go7wN9VKTvjaN+8/1qN1fR1koDyjgMNFJSl3/s="; # FIXME: run nix store prefetch-file and fill in
    };
    sdcv = fetchurl {
      url = "https://github.com/Dushistov/sdcv/archive/refs/tags/v0.5.5.tar.gz";
      # upstream md5: 265dbfda83a57810595d156877f3e6fd
      hash = "sha256-TSUZ6PhHm5MB3JHpzaPh7v7xmXDs4OjAXwx7et5dyUs="; # FIXME: run nix store prefetch-file and fill in
    };
    sdl2 = fetchurl {
      url = "https://github.com/libsdl-org/SDL/releases/download/release-2.32.8/SDL2-2.32.8.tar.gz";
      # upstream md5: 7df28be966308a4a51aac87f4e0cf16a
      hash = "sha256-DKg+nJsx4YKIx+yBEQjli6wfG7XsZXetOGgw6sUceH4="; # FIXME: run nix store prefetch-file and fill in
    };
    sqlite = fetchurl {
      url = "https://sqlite.org/2025/sqlite-amalgamation-3500200.zip";
      # upstream md5: 7fec108df759eec20eddfc3d5b48ebba
      hash = "sha256-OHmR3ig0tdoolBGf9Bc6nqB3nqVevPU9mkCyTR3CSE4="; # FIXME: run nix store prefetch-file and fill in
    };
    tar = fetchurl {
      url = "http://ftpmirror.gnu.org/tar/tar-1.34.tar.gz";
      # upstream md5: 9d5949e4c2d9665546ac65dafc0e726a
      hash = "sha256-A9kIz1doz+a3rViMkhxu0hrKv7K3m3iNEzBFNQdkeu0="; # FIXME: run nix store prefetch-file and fill in
    };
    tesseract = fetchurl {
      url = "https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.5.1.tar.gz";
      # upstream md5: dbc5e603ddde25bdec84c30ac47a2afb
      hash = "sha256-p6Pyp0IMtqapTYDCQWPhg88dLxvtLfO7w5fIGAilcjc="; # FIXME: run nix store prefetch-file and fill in
    };
    utf8proc = fetchurl {
      url = "https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.10.0.tar.gz";
      # upstream md5: faa0bbe8f5763da45f2dfb5f863f0400
      hash = "sha256-b08bY52qbcqfgLxdsSM+nLqjGmd5CIcQYWCzPvdD8TY="; # FIXME: run nix store prefetch-file and fill in
    };
    xz = fetchurl {
      url = "https://github.com/tukaani-project/xz/releases/download/v5.8.1/xz-5.8.1.tar.xz";
      # upstream md5: cf5e1feb023d22c6bdaa30e84ef3abe3
      hash = "sha256-C1T3nfhZElBN4LFK7Hlx4/lkSRrxgS2DRHAFgHUTzZ4="; # FIXME: run nix store prefetch-file and fill in
    };
    zlib = fetchurl {
      url = "https://github.com/madler/zlib/releases/download/v1.3.1/zlib-1.3.1.tar.xz";
      # upstream md5: 5e6af153311327e516690d300527ec9e
      hash = "sha256-OO+WuN/lENQnB9nHgYd5FHklQRM+GHCEFGO/pz+IPjI="; # FIXME: run nix store prefetch-file and fill in
    };
    zstd = fetchurl {
      url = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz";
      # upstream md5: 780fc1896922b1bc52a4e90980cdda48
      hash = "sha256-6zPlH0mhXgI5UM14Jcp0pKK0Pbg1SCWsJPwbfuCeb6M="; # FIXME: run nix store prefetch-file and fill in
    };
  };

  # Git checkouts (`DOWNLOAD GIT <rev> <remote>` in koreader-base).
  # Each fetches to base/thirdparty/<name>/build/downloads/source.
  gitSources = {
    djvulibre = fetchgit {
      url = "https://gitlab.com/koreader/djvulibre.git";
      rev = "6a1e5ba1c9ef81c205a4b270c3f121a1e106f4fc";
      hash = "sha256-0YHiKLO5eqD1rGsF4MwaP4IQwdyz31qFyC70SiGxgW8="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    fbink = fetchgit {
      url = "https://github.com/NiLuJe/FBInk.git";
      rev = "8ce07a0c6bad4b7e1300239dcf7bba1b828e1c55";
      hash = "sha256-lTG3mfBHpHbqb0wFbGbg91m7FFHB1QhEh6pXqJwhjhA="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    ffi-cdecl = fetchgit {
      url = "https://github.com/koreader/ffi-cdecl.git";
      rev = "ea45fb34782a29738334e250e820c825d75e5087";
      hash = "sha256-voN75q0JFo0578DpFYpPpNTjSitNGSA63y1wCfrDqBg="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    kobo-usbms = fetchgit {
      url = "https://github.com/koreader/KoboUSBMS.git";
      rev = "a35a8f639699deaae2e2ee446b5f6c2d2096c1bb";
      hash = "sha256-hgrugMYbnb5e0YCbfGftWarNvECJsqAc/8ka1ZAziic="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    libjpeg-turbo = fetchgit {
      url = "https://github.com/libjpeg-turbo/libjpeg-turbo.git";
      rev = "7723f50f3f66b9da74376e6d8badb6162464212c";
      hash = "sha256-uhLfViLUjM5uG2u9wlDqJQs19GWdbMniTFZcgBNQQvE="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    libk2pdfopt = fetchgit {
      url = "https://github.com/koreader/libk2pdfopt.git";
      rev = "59ced371378312d8f332d9a35f5b4a3c33b18954";
      hash = "sha256-Z5L6iGZcMG1anKM9oqdNEhPvJXHyzNYSLaGJWagNRPw="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lj-wpaclient = fetchgit {
      url = "https://github.com/koreader/lj-wpaclient.git";
      rev = "0d5c8ee336b699dbb35850a7336d24e89e1aac24";
      hash = "sha256-m50+7D+LWl5LTqJttNUrHZnQM1FFXS9RbLglOuR9EQQ="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lodepng = fetchgit {
      url = "https://github.com/lvandeve/lodepng.git";
      rev = "0b1d9ccfc2093e5d6620cd9a11d03ee6ff6705f5";
      hash = "sha256-wskSBmAB/jT+t+ArGtLghSbdUAty9gbon8wMnpIeiYU="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lua-Spore = fetchgit {
      url = "https://framagit.org/fperrad/lua-Spore";
      rev = "e4223b8c9814721afefd4e1395eb437eee46ca96";
      hash = "sha256-VlttTYI9qeKxiYuIlS34sO/ozf4uzd9MhVl3m5gRaag="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lua-htmlparser = fetchgit {
      url = "https://github.com/msva/lua-htmlparser";
      rev = "5ce9a775a345cf458c0388d7288e246bb1b82bff";
      hash = "sha256-kMhS7uUVeYRYrJU7VsbRH0aC54F/jaVWh7pdelLmasQ="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lua-rapidjson = fetchgit {
      url = "https://github.com/NiLuJe/lua-rapidjson";
      rev = "e84973356255bde06a70ce6263a3a0ef5c8f4ad4";
      hash = "sha256-xsbf8AYTmGcKgNefFdQJ197aj9Z7BHvAYVgbjhAMfJ0="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luajit = fetchgit {
      url = "https://github.com/LuaJIT/LuaJIT";
      rev = "f9140a622a0c44a99efb391cc1c2358bc8098ab7";
      hash = "sha256-jBweRsh7sFYv3yuOGAq2esJVEyrGIoMF+GwWlMLmMko="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luajson = fetchgit {
      url = "https://github.com/harningt/luajson.git";
      rev = "6ecaf9bea8b121a9ffca5a470a2080298557b55d";
      hash = "sha256-Y2GpaMWXoiGtbjlO8/NP/35PgRuzTkwXmxIetE8D+IM="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luasec = fetchgit {
      url = "https://github.com/brunoos/luasec";
      rev = "4c06287052d68fdbe7429b8f967cdc8ee94aa44a";
      hash = "sha256-sZu6acBs3Gy1h74sK7wU2NvPOd3kDaqeIeBKJ/pJv/E="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    luasocket = fetchgit {
      url = "https://github.com/lunarmodules/luasocket";
      rev = "e3ca4a767a68d127df548d82669aba3689bd84f4";
      hash = "sha256-OFz07+Wdhiz/JhQ7AZjsklzM15Z9kJz2KUQpvcVnGsk="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    lunasvg = fetchgit {
      url = "https://github.com/sammycage/lunasvg.git";
      rev = "59d6f6ba835c1b7c7a0f9d4ea540ec3981777885";
      hash = "sha256-g6jszT36JeaO6C6idGHx9efUwjsPYwoJJJ+2xo/WKdQ="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    minizip = fetchgit {
      url = "https://github.com/nmoinvaz/minizip";
      rev = "0b46a2b4ca317b80bc53594688883f7188ac4d08";
      hash = "sha256-0ARFhLNex3nUJX9PIp1KxL/VY7DTbOedUkKEupCF1Uw="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    nanosvg = fetchgit {
      url = "https://github.com/memononen/nanosvg.git";
      rev = "ea6a6aca009422bba0dbad4c80df6e6ba0c82183";
      hash = "sha256-zop4QF6gawQjjsVPb9xqfMqUSawACR6/qjArT1Noqu4="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    openlipclua = fetchgit {
      url = "https://github.com/notmarek/openlipclua.git";
      rev = "96c2d16696a482664b4e84eb3b6d851f807a44d1";
      hash = "sha256-oHHMXCZVuZp2CTqUOOjZ6UiDNK1eSa1w9TSDgi7+Yis="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    popen-noshell = fetchgit {
      url = "https://github.com/famzah/popen-noshell.git";
      rev = "e715396a4951ee91c40a98d2824a130f158268bb";
      hash = "sha256-oIAL6fMw6UfjG2CnV5zK1cZIkCdt68hEbq45dTRpSEM="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    turbo = fetchgit {
      url = "https://github.com/kernelsauce/turbo";
      rev = "7fe88c2b99ff9bd6d6df3ee3c4077ea8a7d1e6a3";
      hash = "sha256-4QbgBs/sUlaQ/SBQMUm/yvWnrjEUR1tQf1CHW8POO2g="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
    zsync2 = fetchgit {
      url = "https://github.com/NiLuJe/zsync2.git";
      rev = "e281e1eb4466ff6b3866c25dbe62a3e150fa5bfd";
      hash = "sha256-gaCX7SA+xF7GpxdvFS+qsBW/3igjve8FXfxGX6N9FxE="; # FIXME: run `nix-prefetch-git --leave-dotGit` and fill in
      fetchSubmodules = true;
      # koreader-base's own build re-checks out the pinned
      # revision via git, so it needs a real .git dir.
      leaveDotGit = true;
    };
  };
}
