{
  lib,
  stdenv,
  buildPackages,
  fetchFromGitHub,
  fetchurl,
  fetchgit,
  pkgsi686Linux,
  cacert,

  cmake,
  ninja,
  meson,
  pkg-config,
  git,
  gnupatch,
  gettext,
  unzip,
  p7zip,
  wget,
  curl,
  nasm,
  autoconf,
  automake,
  libtool,
  gnumake,
  perl,
  file,
  makeWrapper,
  util-linux,
  python3,
  zlib,
  sqlite,
  utf8proc,
  libpng,
  giflib,
  fribidi,
  libwebp,
  xxHash,
  zstd,
  zeromq,
  czmq,

  coreutils,
  writeShellScriptBin,
}:
let
  version = "2026.07.1";

  # Generated by nix/pkgs/koreader/generate-sources.py from koreader-base's
  # own thirdparty DOWNLOAD pins (koreader-base's cmake build otherwise
  # fetches these itself mid-build, which the nix sandbox can't allow).
  sources = import ./koreader/sources.nix { inherit fetchurl fetchgit; };

  # LuaJIT's `buildvm` host tool must be built with a compiler whose pointer
  # width matches the (32-bit ARM) target; nix cross builds have no -m32
  # multilib, so a real i686 compiler is used instead (see
  # nix/pkgs/koreader/patches/luajit-host-cc32.patch).
  luajitHostCC32 = "${pkgsi686Linux.gcc}/bin/gcc";

  # meson's cross/native toolchain ini files koreader-base generates
  # hardcode the bare command name "pkg-config"; nixpkgs doesn't put a
  # bare-named one on PATH for cross builds (only a target-prefixed one
  # under `buildPackages`, since the plain `pkg-config` nativeBuildInput is
  # actually cross-*compiled* to run on the target, not runnable here), so
  # pass its absolute path explicitly (see makefile-defs-nix-cross.patch).
  mesonPkgConfig = "${buildPackages.pkg-config}/bin/${stdenv.hostPlatform.config}-pkg-config";

  # nix sandboxed builds have no /usr/bin/env, breaking `#!/usr/bin/env foo`
  # shebangs in sources koreader-base extracts mid-build (too late for
  # nixpkgs' own patchShebangs, and bash function export doesn't reliably
  # propagate through make/ninja's sub-shells — see koenv-patchshebangs.patch).
  patchShebangsScript = ./koreader/patch-shebangs.sh;

  fake-dbus = writeShellScriptBin "dbus-monitor" ''
    export PATH="${lib.makeBinPath [ coreutils ]}"
    sleep infinity
  '';

  # Populate a thirdparty dependency's CMake staging output directly from a
  # matching nixpkgs armv7l cross package instead of compiling it from
  # source: koreader-base's own build for these is unpatched (or only
  # patched for cross-compile quirks gated off for TARGET=remarkable), so
  # compiling our own copy would just duplicate what nixpkgs already built,
  # for zero behavioral difference and non-trivial build time. Some of
  # these (zlib, libpng, libwebp) are consumed by *other* thirdparty deps'
  # own configure step (via CMake's find_package, root-pathed at
  # STAGING_DIR, or meson pkg-config, PKG_CONFIG_LIBDIR-pathed at
  # STAGING_DIR/lib/pkgconfig - see Makefile.defs) - copying headers/libs/
  # pkgconfig files into STAGING_DIR here makes them transparently visible
  # the same way a real build's install step would.
  # DOWNLOAD is kept (cheap - it's already a local nix store symlink, see
  # sources.urlSources below) purely to reuse external_project()'s
  # validated download/extract machinery; only CONFIGURE/BUILD are skipped.
  vendorThirdparty =
    {
      name,
      md5,
      url,
      sharedLibs,
      headers,
      lib_,
    }:
    ''
      cat > base/thirdparty/${name}/CMakeLists.txt <<'KOREADER_NIX_VENDORED'
      # Build in source tree (there's no real build, just an install step;
      # this keeps external_project()'s implicit no-op "build" step, which
      # cd's into BINARY_DIR, pointed at a directory that actually exists).
      set(BINARY_DIR ''${SOURCE_DIR})

      list(APPEND INSTALL_CMD
          COMMAND ''${CMAKE_COMMAND} -E make_directory ''${STAGING_DIR}/include ''${STAGING_DIR}/lib
          COMMAND ''${CMAKE_COMMAND} -E copy_directory ${headers}/include ''${STAGING_DIR}/include
          COMMAND ''${CMAKE_COMMAND} -E copy_directory ${lib_}/lib ''${STAGING_DIR}/lib
          COMMAND sh -c "[ -d ${headers}/lib/pkgconfig ] && mkdir -p ''${STAGING_DIR}/lib/pkgconfig && cp -a ${headers}/lib/pkgconfig/. ''${STAGING_DIR}/lib/pkgconfig/ || :"
          COMMAND chmod -R u+w ''${STAGING_DIR}/include ''${STAGING_DIR}/lib
      )
      if(NOT MONOLIBTIC)
      ${lib.concatMapStrings (
        l: "    append_shared_lib_install_commands(INSTALL_CMD ${l.name} VERSION ${toString l.version})\n"
      ) sharedLibs}
      endif()
      external_project(
          DOWNLOAD URL ${md5}
          ${url}
          INSTALL_COMMAND ''${INSTALL_CMD}
      )
      KOREADER_NIX_VENDORED
    '';
in
stdenv.mkDerivation {
  pname = "koreader";
  inherit version;

  src = fetchFromGitHub {
    owner = "koreader";
    repo = "koreader";
    rev = "v${version}";
    fetchSubmodules = true;
    hash = "sha256-395G5bu0gs0oKOc/CfKNeal66vgXBDgHSpopoQ0GRzw=";
  };

  nativeBuildInputs = [
    cmake
    ninja
    meson
    pkg-config
    git
    gnupatch
    gettext
    unzip
    p7zip
    wget
    curl
    nasm
    autoconf
    automake
    libtool
    gnumake
    perl
    file
    makeWrapper
    util-linux
    python3
  ];

  # Several thirdparty deps (fribidi, glib, harfbuzz, ...) build small
  # native codegen tools with meson's "build machine" compiler as part of
  # their cross build; only the cross (armv7l) compiler is on PATH by
  # default in a cross derivation, so a real build-machine one is needed too.
  depsBuildBuild = [ buildPackages.stdenv.cc ];

  postPatch = ''
    patch -p1 -d base < ${./koreader/patches/makefile-defs-nix-cross.patch}
    patch -p1 -d base < ${./koreader/patches/luajit-host-cc32.patch}
    patch -p1 -d base < ${./koreader/patches/pin-tag-revs-to-shas.patch}
    patch -p1 -d base < ${./koreader/patches/koenv-patchshebangs.patch}
  ''
  + vendorThirdparty {
    name = "zlib";
    md5 = "be8a129ec5d60c5084911fd7ea16d84e";
    url = "https://github.com/madler/zlib/releases/download/v1.3.2/zlib-1.3.2.tar.xz";
    sharedLibs = [
      {
        name = "z";
        version = 1;
      }
    ];
    headers = zlib.dev;
    lib_ = zlib;
  }
  + vendorThirdparty {
    name = "libpng";
    md5 = "92972b05f1895240139f749ff24afce8";
    url = "https://github.com/pnggroup/libpng/archive/refs/tags/v1.6.58.tar.gz";
    sharedLibs = [
      {
        name = "png16";
        version = 16;
      }
    ];
    headers = libpng.dev;
    lib_ = libpng;
  }
  + vendorThirdparty {
    name = "libwebp";
    md5 = "cceb6447180f961473b181c9ef38b630";
    url = "https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.6.0.tar.gz";
    sharedLibs = [
      {
        name = "sharpyuv";
        version = 0;
      }
      {
        name = "webpdemux";
        version = 2;
      }
      {
        name = "webp";
        version = 7;
      }
    ];
    headers = libwebp;
    lib_ = libwebp;
  }
  + vendorThirdparty {
    name = "utf8proc";
    md5 = "09773a9a9c4029b1e547fe398e555411";
    url = "https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.11.3.tar.gz";
    sharedLibs = [
      {
        name = "utf8proc";
        version = 3;
      }
    ];
    headers = utf8proc;
    lib_ = utf8proc;
  }
  + vendorThirdparty {
    name = "giflib";
    md5 = "a70e90ff780e9ebee9cb84b82bbd46a7";
    url = "https://sourceforge.net/projects/giflib/files/giflib-6.x/giflib-6.1.3.tar.gz";
    sharedLibs = [
      {
        name = "gif";
        version = 7;
      }
    ];
    headers = giflib;
    lib_ = giflib;
  }
  + vendorThirdparty {
    name = "xxhash";
    md5 = "599804eb9555e51c05f1b821f9212a07";
    url = "https://github.com/Cyan4973/xxHash/archive/refs/tags/v0.8.3.tar.gz";
    sharedLibs = [
      {
        name = "xxhash";
        version = 0;
      }
    ];
    headers = xxHash;
    lib_ = xxHash;
  }
  + vendorThirdparty {
    name = "zstd";
    md5 = "780fc1896922b1bc52a4e90980cdda48";
    url = "https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-1.5.7.tar.gz";
    sharedLibs = [
      {
        name = "zstd";
        version = 1;
      }
    ];
    headers = zstd.dev;
    lib_ = zstd.out;
  }
  + vendorThirdparty {
    name = "fribidi";
    md5 = "333ad150991097a627755b752b87f9ff";
    url = "https://github.com/fribidi/fribidi/releases/download/v1.0.16/fribidi-1.0.16.tar.xz";
    sharedLibs = [
      {
        name = "fribidi";
        version = 0;
      }
    ];
    headers = fribidi.dev;
    lib_ = fribidi;
  }
  + vendorThirdparty {
    name = "libzmq";
    md5 = "ae933b1e98411fd7cb8309f9502d2737";
    url = "https://github.com/zeromq/libzmq/releases/download/v4.3.5/zeromq-4.3.5.tar.gz";
    sharedLibs = [
      {
        name = "zmq";
        version = 5;
      }
    ];
    headers = zeromq;
    lib_ = zeromq;
  }
  + vendorThirdparty {
    name = "czmq";
    md5 = "471e9ec120fc66a2fe2aae14359e3cfa";
    url = "https://github.com/zeromq/czmq/releases/download/v4.2.1/czmq-4.2.1.tar.gz";
    sharedLibs = [
      {
        name = "czmq";
        version = 4;
      }
    ];
    headers = czmq;
    lib_ = czmq;
  }
  + ''
    # nixpkgs' own patchShebangs only runs automatically in fixupPhase (after
    # install), too late for our custom buildPhase; fix up scripts already
    # present in $src ourselves. Scripts koreader-base extracts mid-build are
    # handled separately via $PATCH_SHEBANGS (see koenv-patchshebangs.patch).
    # Scoped to base/ (all `make all` actually builds is `base` + `mo`, and
    # `mo` only runs msgfmt, no scripts) rather than the whole source tree:
    # top-level scripts like koreader.sh/enable-wifi.sh/spinning_zsync/the
    # terminal plugin's shfm are meant to run *on the reMarkable* at runtime
    # with a plain #!/bin/sh, never during this (x86_64) build - patching
    # them would point them at a build-machine bash, wrongly, and would drag
    # bash's own closure into koreader's runtime closure for no reason.
    patchShebangs base
  ''
  + lib.concatStrings (
    lib.mapAttrsToList (name: src: ''
      mkdir -p base/thirdparty/${name}/build/downloads
      ln -s ${src} base/thirdparty/${name}/build/downloads/${src.name}
    '') sources.urlSources
  )
  + lib.concatStrings (
    lib.mapAttrsToList (name: src: ''
      mkdir -p base/thirdparty/${name}/build/downloads
      cp -a ${src} base/thirdparty/${name}/build/downloads/source
      chmod -R u+w base/thirdparty/${name}/build/downloads/source
    '') sources.gitSources
  )
  # curl's own build additionally fetches Mozilla's CA bundle directly
  # from curl.se (outside koreader-base's usual DOWNLOAD machinery); reuse
  # nixpkgs' cacert instead. fetch-ca-bundle.sh treats a pre-existing file
  # as good enough and only warns (doesn't fail) if the live fetch fails.
  + ''
    mkdir -p base/thirdparty/curl/build/downloads
    cp ${cacert}/etc/ssl/certs/ca-bundle.crt base/thirdparty/curl/build/downloads/ca-bundle.crt
  '';

  # koreader's own Makefile drives cmake/meson itself (see `buildPhase`);
  # suppress their setup-hooks' automatic configurePhase overrides (there's
  # no top-level CMakeLists.txt/meson.build — cmake's lives under base/cmake,
  # and meson is invoked per-thirdparty-dependency by koreader's own build).
  dontUseCmakeConfigure = true;
  dontUseMesonConfigure = true;

  makeFlags = [
    "TARGET=remarkable"
    "CHOST=${stdenv.hostPlatform.config}"
    "LUAJIT_HOST_CC32=${luajitHostCC32}"
    "MESON_PKGCONFIG=${mesonPkgConfig}"
    "PATCH_SHEBANGS=${patchShebangsScript}"
    "VERSION=v${version}"
    "INSTALL_DIR=install"
    "PARALLEL_JOBS=$(NIX_BUILD_CORES)"
  ];

  buildPhase = ''
    runHook preBuild
    make $makeFlags all
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    install -d $out/koreader
    # `all`'s $(INSTALL_DIR)/koreader tree is built out of symlinks back
    # into the build tree, so dereference them into real files under $out.
    cp -aL install/koreader/. $out/koreader/

    # Split-out debug symbols aren't used by anything at runtime (koreader's
    # own crash handler just captures a plain lua traceback, no gdb/addr2line
    # involved), but embed the cross-compiler's own store path in their DWARF
    # info - keeping them drags the entire ~350MB armv7 gcc toolchain into
    # koreader's runtime closure for no benefit.
    find $out/koreader -name '*.dbg' -delete

    # `all` installs `resources`, `l10n` and `tools` verbatim (unfiltered);
    # `make update`'s own release packaging (Makefile's UPDATE_PATH_EXCLUDES)
    # drops these same paths from the official release zip - translation
    # sources/templates aren't needed at runtime (only the compiled .mo
    # files are), `resources/fonts` is a duplicate of the top-level `fonts/`
    # dir `all` itself symlinks it into, and `tools/` is maintainer-only.
    rm -rf $out/koreader/l10n/templates
    rm -f $out/koreader/l10n/*/*.po
    rm -rf $out/koreader/resources/fonts
    rm -rf $out/koreader/resources/icons/src
    rm -rf $out/koreader/tools

    # koreader-base bundles its own copy of every runtime shared library it
    # links against (built for embedded targets with no system package
    # manager); on nix, that just duplicates bytes nixpkgs already builds.
    # Swap the ones with an unpatched, same/near version nixpkgs equivalent
    # (same SONAME confirmed for each) for a symlink into the nix store -
    # unlike a copy, a real symlink shrinks $out by the swapped library's
    # size instead of just adding a duplicate.
    rm -f $out/koreader/libs/libz.so.1
    ln -s ${zlib}/lib/libz.so.1 $out/koreader/libs/libz.so.1
    rm -f $out/koreader/libs/libsqlite3.so.0
    ln -s ${sqlite.out}/lib/libsqlite3.so.0 $out/koreader/libs/libsqlite3.so.0
    rm -f $out/koreader/libs/libutf8proc.so.3
    ln -s ${utf8proc}/lib/libutf8proc.so.3 $out/koreader/libs/libutf8proc.so.3
    rm -f $out/koreader/libs/libpng16.so.16
    ln -s ${libpng}/lib/libpng16.so.16 $out/koreader/libs/libpng16.so.16
    rm -f $out/koreader/libs/libgif.so.7
    ln -s ${giflib}/lib/libgif.so.7 $out/koreader/libs/libgif.so.7
    rm -f $out/koreader/libs/libfribidi.so.0
    ln -s ${fribidi}/lib/libfribidi.so.0 $out/koreader/libs/libfribidi.so.0
    rm -f $out/koreader/libs/libxxhash.so.0
    ln -s ${xxHash}/lib/libxxhash.so.0 $out/koreader/libs/libxxhash.so.0
    rm -f $out/koreader/libs/libzstd.so.1
    ln -s ${zstd.out}/lib/libzstd.so.1 $out/koreader/libs/libzstd.so.1
    rm -f $out/koreader/libs/libsharpyuv.so.0
    ln -s ${libwebp}/lib/libsharpyuv.so.0 $out/koreader/libs/libsharpyuv.so.0
    rm -f $out/koreader/libs/libwebpdemux.so.2
    ln -s ${libwebp}/lib/libwebpdemux.so.2 $out/koreader/libs/libwebpdemux.so.2
    rm -f $out/koreader/libs/libwebp.so.7
    ln -s ${libwebp}/lib/libwebp.so.7 $out/koreader/libs/libwebp.so.7
    rm -f $out/koreader/libs/libzmq.so.5
    ln -s ${zeromq}/lib/libzmq.so.5 $out/koreader/libs/libzmq.so.5
    # czmq's own patches include a real upstream bugfix (a thread-name-prefix
    # env var mixup in zsys_init(), see koreader-base's
    # thirdparty/czmq/fix_prefix_handling.patch) that nixpkgs' unpatched
    # build lacks; low-impact (debug thread naming only) but swapping this
    # one is a deliberate, slightly less conservative call.
    rm -f $out/koreader/libs/libczmq.so.4
    ln -s ${czmq}/lib/libczmq.so.4 $out/koreader/libs/libczmq.so.4
    # These swaps pull nixpkgs' default-config builds in as runtime deps
    # (e.g. libwebp brings libtiff/lerc/libdeflate/libjpeg-turbo; zeromq
    # brings libsodium for CURVE support) that koreader's own minimal
    # from-source builds don't need. In isolation that makes *this
    # package's own* closure bigger, but on a NixOS system these are
    # commonly already-shared store paths pulled in by other packages -
    # preferring the system-wide copy over a private duplicate is the
    # right default here.
    # libunibreak bundled here is 7.0 (SONAME 7); nixpkgs is still on 6.1
    # (SONAME 6), so no swap is possible until nixpkgs catches up.

    # libstdc++.so.6 is koreader's own bundled copy of the cross-compiler's
    # C++ runtime - but stdenv.cc.cc.lib is *already* a mandatory closure
    # member (every C++ .so here links against it), so this swap adds no
    # new closure weight at all, purely removing the largest duplicate file
    # in libs/ (~2MB, bigger than the whole Tier A batch above combined).
    rm -f $out/koreader/libs/libstdc++.so.6
    ln -s ${stdenv.cc.cc.lib}/lib/libstdc++.so.6 $out/koreader/libs/libstdc++.so.6

    # data/ca-bundle.crt is koreader's own runtime copy of the CA bundle we
    # already fed nixpkgs' cacert into at build time (see postPatch above,
    # for curl's build-time fetch-ca-bundle.sh) - byte-identical, so no need
    # to ship a second copy of it too.
    rm -f $out/koreader/data/ca-bundle.crt
    ln -s ${cacert}/etc/ssl/certs/ca-bundle.crt $out/koreader/data/ca-bundle.crt

    # Mirror the handful of remarkable-specific extras that `make update`
    # would otherwise symlink in (skipping the release-zip packaging step,
    # which needs a real git history for versioning that we don't have).
    cp platform/common/spinning_zsync $out/koreader/
    cp platform/remarkable/koreader.sh $out/koreader/
    cp resources/koreader.png $out/koreader/icon.png
    cp platform/remarkable/external.manifest.json $out/koreader/
    cp platform/remarkable/README.md $out/koreader/README_remarkable.md
    cp platform/remarkable/button-listen.service $out/koreader/
    cp platform/remarkable/disable-wifi.sh $out/koreader/
    cp platform/remarkable/enable-wifi.sh $out/koreader/
    cp platform/remarkable/koreader.service $out/koreader/

    # Instead of detecting xochitl, detect nixos in general.
    substituteInPlace $out/koreader/frontend/device.lua \
      --replace-fail /usr/bin/xochitl /etc/NIXOS

    # This compares /tmp/koreader.sh (which the *official* koreader.sh
    # startup script copies itself to on launch, as a marker of what's
    # currently running) against the installed one, to prompt a restart
    # after koreader's own self-updater drops in a new version. We launch
    # luajit directly (no koreader.sh, no self-updater - nix owns
    # versioning), so /tmp/koreader.sh never exists and this would always
    # be stuck reporting a pending update.
    substituteInPlace $out/koreader/frontend/device/remarkable/device.lua \
      --replace-fail \
        'local script_utd = md5.sumFile("/tmp/koreader.sh") == md5.sumFile("koreader.sh")' \
        'local script_utd = true' \
      --replace-fail \
        'local manifest_utd = md5.sumFile("/tmp/external.manifest.json") == md5.sumFile("external.manifest.json")' \
        'local manifest_utd = true'

    mkdir -p $out/bin
    makeWrapper $out/koreader/luajit $out/bin/koreader \
      --chdir $out/koreader \
      --add-flags $out/koreader/reader.lua \
      --set KO_MULTIUSER 1 \
      --set KO_DONT_GRAB_INPUT 1 \
      --set LD_PRELOAD /run/current-system/sw/lib/librm2fb_client.so \
      --set PATH ${
        lib.makeBinPath [
          coreutils
          fake-dbus
        ]
      }

    runHook postInstall
  '';

  meta.mainProgram = "koreader";
}
