{
  lib,
  stdenv,
  buildPackages,
  fetchFromGitHub,
  fetchurl,
  fetchgit,
  pkgsi686Linux,
  cacert,

  cmake,
  ninja,
  meson,
  pkg-config,
  git,
  gnupatch,
  gettext,
  unzip,
  p7zip,
  wget,
  curl,
  nasm,
  autoconf,
  automake,
  libtool,
  gnumake,
  perl,
  file,
  makeWrapper,
  util-linux,
  python3,
  zlib,
  sqlite,
  utf8proc,
  libpng,
  giflib,
  libunibreak,

  coreutils,
  writeShellScriptBin,
}:
let
  version = "2025.08";

  # Generated by nix/pkgs/koreader/generate-sources.py from koreader-base's
  # own thirdparty DOWNLOAD pins (koreader-base's cmake build otherwise
  # fetches these itself mid-build, which the nix sandbox can't allow).
  sources = import ./koreader/sources.nix { inherit fetchurl fetchgit; };

  # LuaJIT's `buildvm` host tool must be built with a compiler whose pointer
  # width matches the (32-bit ARM) target; nix cross builds have no -m32
  # multilib, so a real i686 compiler is used instead (see
  # nix/pkgs/koreader/patches/luajit-host-cc32.patch).
  luajitHostCC32 = "${pkgsi686Linux.gcc}/bin/gcc";

  # meson's cross/native toolchain ini files koreader-base generates
  # hardcode the bare command name "pkg-config"; nixpkgs doesn't put a
  # bare-named one on PATH for cross builds (only a target-prefixed one
  # under `buildPackages`, since the plain `pkg-config` nativeBuildInput is
  # actually cross-*compiled* to run on the target, not runnable here), so
  # pass its absolute path explicitly (see makefile-defs-nix-cross.patch).
  mesonPkgConfig = "${buildPackages.pkg-config}/bin/${stdenv.hostPlatform.config}-pkg-config";

  # nix sandboxed builds have no /usr/bin/env, breaking `#!/usr/bin/env foo`
  # shebangs in sources koreader-base extracts mid-build (too late for
  # nixpkgs' own patchShebangs, and bash function export doesn't reliably
  # propagate through make/ninja's sub-shells — see koenv-patchshebangs.patch).
  patchShebangsScript = ./koreader/patch-shebangs.sh;

  fake-dbus = writeShellScriptBin "dbus-monitor" ''
    export PATH="${lib.makeBinPath [ coreutils ]}"
    sleep infinity
  '';
in
stdenv.mkDerivation {
  pname = "koreader";
  inherit version;

  src = fetchFromGitHub {
    owner = "koreader";
    repo = "koreader";
    rev = "v${version}";
    fetchSubmodules = true;
    hash = "sha256-lkXpmvde1PPJRocnRpmuu4AeCv/0Mql40Aw5WIZfj5s=";
  };

  nativeBuildInputs = [
    cmake
    ninja
    meson
    pkg-config
    git
    gnupatch
    gettext
    unzip
    p7zip
    wget
    curl
    nasm
    autoconf
    automake
    libtool
    gnumake
    perl
    file
    makeWrapper
    util-linux
    python3
  ];

  # Several thirdparty deps (fribidi, glib, harfbuzz, ...) build small
  # native codegen tools with meson's "build machine" compiler as part of
  # their cross build; only the cross (armv7l) compiler is on PATH by
  # default in a cross derivation, so a real build-machine one is needed too.
  depsBuildBuild = [ buildPackages.stdenv.cc ];

  postPatch = ''
    patch -p1 -d base < ${./koreader/patches/makefile-defs-nix-cross.patch}
    patch -p1 -d base < ${./koreader/patches/luajit-host-cc32.patch}
    patch -p1 -d base < ${./koreader/patches/pin-tag-revs-to-shas.patch}
    patch -p1 -d base < ${./koreader/patches/koenv-patchshebangs.patch}

    # nixpkgs' own patchShebangs only runs automatically in fixupPhase (after
    # install), too late for our custom buildPhase; fix up scripts already
    # present in $src ourselves. Scripts koreader-base extracts mid-build are
    # handled separately via $PATCH_SHEBANGS (see koenv-patchshebangs.patch).
    # Scoped to base/ (all `make all` actually builds is `base` + `mo`, and
    # `mo` only runs msgfmt, no scripts) rather than the whole source tree:
    # top-level scripts like koreader.sh/enable-wifi.sh/spinning_zsync/the
    # terminal plugin's shfm are meant to run *on the reMarkable* at runtime
    # with a plain #!/bin/sh, never during this (x86_64) build - patching
    # them would point them at a build-machine bash, wrongly, and would drag
    # bash's own closure into koreader's runtime closure for no reason.
    patchShebangs base
  ''
  + lib.concatStrings (
    lib.mapAttrsToList (name: src: ''
      mkdir -p base/thirdparty/${name}/build/downloads
      ln -s ${src} base/thirdparty/${name}/build/downloads/${src.name}
    '') sources.urlSources
  )
  + lib.concatStrings (
    lib.mapAttrsToList (name: src: ''
      mkdir -p base/thirdparty/${name}/build/downloads
      cp -a ${src} base/thirdparty/${name}/build/downloads/source
      chmod -R u+w base/thirdparty/${name}/build/downloads/source
    '') sources.gitSources
  )
  # curl's own build additionally fetches Mozilla's CA bundle directly
  # from curl.se (outside koreader-base's usual DOWNLOAD machinery); reuse
  # nixpkgs' cacert instead. fetch-ca-bundle.sh treats a pre-existing file
  # as good enough and only warns (doesn't fail) if the live fetch fails.
  + ''
    mkdir -p base/thirdparty/curl/build/downloads
    cp ${cacert}/etc/ssl/certs/ca-bundle.crt base/thirdparty/curl/build/downloads/ca-bundle.crt
  '';

  # koreader's own Makefile drives cmake/meson itself (see `buildPhase`);
  # suppress their setup-hooks' automatic configurePhase overrides (there's
  # no top-level CMakeLists.txt/meson.build — cmake's lives under base/cmake,
  # and meson is invoked per-thirdparty-dependency by koreader's own build).
  dontUseCmakeConfigure = true;
  dontUseMesonConfigure = true;

  makeFlags = [
    "TARGET=remarkable"
    "CHOST=${stdenv.hostPlatform.config}"
    "LUAJIT_HOST_CC32=${luajitHostCC32}"
    "MESON_PKGCONFIG=${mesonPkgConfig}"
    "PATCH_SHEBANGS=${patchShebangsScript}"
    "VERSION=v${version}"
    "INSTALL_DIR=install"
    "PARALLEL_JOBS=$(NIX_BUILD_CORES)"
  ];

  buildPhase = ''
    runHook preBuild
    make $makeFlags all
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    install -d $out/koreader
    # `all`'s $(INSTALL_DIR)/koreader tree is built out of symlinks back
    # into the build tree, so dereference them into real files under $out.
    cp -aL install/koreader/. $out/koreader/

    # Split-out debug symbols aren't used by anything at runtime (koreader's
    # own crash handler just captures a plain lua traceback, no gdb/addr2line
    # involved), but embed the cross-compiler's own store path in their DWARF
    # info - keeping them drags the entire ~350MB armv7 gcc toolchain into
    # koreader's runtime closure for no benefit.
    find $out/koreader -name '*.dbg' -delete

    # `all` installs `resources`, `l10n` and `tools` verbatim (unfiltered);
    # `make update`'s own release packaging (Makefile's UPDATE_PATH_EXCLUDES)
    # drops these same paths from the official release zip - translation
    # sources/templates aren't needed at runtime (only the compiled .mo
    # files are), `resources/fonts` is a duplicate of the top-level `fonts/`
    # dir `all` itself symlinks it into, and `tools/` is maintainer-only.
    rm -rf $out/koreader/l10n/templates
    rm -f $out/koreader/l10n/*/*.po
    rm -rf $out/koreader/resources/fonts
    rm -rf $out/koreader/resources/icons/src
    rm -rf $out/koreader/tools

    # koreader-base bundles its own copy of every runtime shared library it
    # links against (built for embedded targets with no system package
    # manager); on nix, that just duplicates bytes nixpkgs already builds.
    # Swap the ones with an unpatched, same/near version nixpkgs equivalent
    # (same SONAME confirmed for each) for a symlink into the nix store -
    # unlike a copy, a real symlink shrinks $out by the swapped library's
    # size instead of just adding a duplicate.
    rm -f $out/koreader/libs/libz.so.1
    ln -s ${zlib}/lib/libz.so.1 $out/koreader/libs/libz.so.1
    rm -f $out/koreader/libs/libsqlite3.so.0
    ln -s ${sqlite.out}/lib/libsqlite3.so.0 $out/koreader/libs/libsqlite3.so.0
    rm -f $out/koreader/libs/libutf8proc.so.3
    ln -s ${utf8proc}/lib/libutf8proc.so.3 $out/koreader/libs/libutf8proc.so.3
    rm -f $out/koreader/libs/libpng16.so.16
    ln -s ${libpng}/lib/libpng16.so.16 $out/koreader/libs/libpng16.so.16
    rm -f $out/koreader/libs/libgif.so.7
    ln -s ${giflib}/lib/libgif.so.7 $out/koreader/libs/libgif.so.7
    rm -f $out/koreader/libs/libunibreak.so.6
    ln -s ${libunibreak}/lib/libunibreak.so.6 $out/koreader/libs/libunibreak.so.6

    # libstdc++.so.6 is koreader's own bundled copy of the cross-compiler's
    # C++ runtime - but stdenv.cc.cc.lib is *already* a mandatory closure
    # member (every C++ .so here links against it), so this swap adds no
    # new closure weight at all, purely removing the largest duplicate file
    # in libs/ (~2MB, bigger than the whole Tier A batch above combined).
    rm -f $out/koreader/libs/libstdc++.so.6
    ln -s ${stdenv.cc.cc.lib}/lib/libstdc++.so.6 $out/koreader/libs/libstdc++.so.6

    # data/ca-bundle.crt is koreader's own runtime copy of the CA bundle we
    # already fed nixpkgs' cacert into at build time (see postPatch above,
    # for curl's build-time fetch-ca-bundle.sh) - byte-identical, so no need
    # to ship a second copy of it too.
    rm -f $out/koreader/data/ca-bundle.crt
    ln -s ${cacert}/etc/ssl/certs/ca-bundle.crt $out/koreader/data/ca-bundle.crt

    # Mirror the handful of remarkable-specific extras that `make update`
    # would otherwise symlink in (skipping the release-zip packaging step,
    # which needs a real git history for versioning that we don't have).
    cp platform/common/spinning_zsync $out/koreader/
    cp platform/remarkable/koreader.sh $out/koreader/
    cp resources/koreader.png $out/koreader/icon.png
    cp platform/remarkable/external.manifest.json $out/koreader/
    cp platform/remarkable/README.md $out/koreader/README_remarkable.md
    cp platform/remarkable/button-listen.service $out/koreader/
    cp platform/remarkable/disable-wifi.sh $out/koreader/
    cp platform/remarkable/enable-wifi.sh $out/koreader/
    cp platform/remarkable/koreader.service $out/koreader/

    # Instead of detecting xochitl, detect nixos in general.
    substituteInPlace $out/koreader/frontend/device.lua \
      --replace-fail /usr/bin/xochitl /etc/NIXOS

    mkdir -p $out/bin
    makeWrapper $out/koreader/luajit $out/bin/koreader \
      --chdir $out/koreader \
      --add-flags $out/koreader/reader.lua \
      --set KO_MULTIUSER 1 \
      --set KO_DONT_GRAB_INPUT 1 \
      --set LD_PRELOAD /run/current-system/sw/lib/librm2fb_client.so \
      --set PATH ${
        lib.makeBinPath [
          coreutils
          fake-dbus
        ]
      }

    runHook postInstall
  '';

  meta.mainProgram = "koreader";
}
